apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml
<%if eq (index .Params `userAuth`) "yes" %>- auth.yml
<% end %>
resources:
- ../../base
- external-secret.yml
<%if eq (index .Params `userAuth`) "yes" %>## userAuth enabled - Oathkeeper proxies to backend instead of ingress
# - ingress.yml
<% else %>- ingress.yml<% end %>
- pdb.yml

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - ENVIRONMENT=production
    - DOMAIN=<% index .Params `productionHostRoot` %>
    - BACKEND_URL=https://<% index .Params `productionBackendSubdomain` %><% index .Params `productionHostRoot` %>
    - FRONTEND_URL=https://<% index .Params `productionFrontendSubdomain` %><% index .Params `productionHostRoot` %>
    - S3_BUCKET=files.<% index .Params `productionHostRoot` %>
