apiVersion: apps/v1
kind: Deployment
metadata:
  name: <% .Name %>
spec:
  template:
    spec:
      # To enable the backend-service account, you can add an entry from infrastructure repo
      # kubernetes/terraform/environments/stage/main.tf's application_policy_list for dev namespaces
      serviceAccountName: default
      containers:
        - name: <% .Name %>
          image: <% index .Params `accountId` %>.dkr.ecr.<% index .Params `region` %>.amazonaws.com/<% .Name %>:last-deployed
          resources:
            requests:
              memory: 64Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 1.0
