const { gql } = require('apollo-server-express');

const typeDefs = gql`
    "User object for the authentication"
    type User {
      """
      The user id that Identity Provider assigned.
      """
      id: ID!
      email: String!
    }
    "Presigned url object"
    type PresignedUrl {
      """
      A presigned url generated by a cloud storage points to a specific file 
      that has been stored or will be stored on a cloud storage
      """
      url: String
      """
      The http request method such as GET, PUT, POST
      """
      method: String 
    }
    "A presigned urls collection that is able to return all presigned urls to a user at the same time. "
    type PresignedUrls {
      """
      The presigned url object for file uploading
      """
      upload: PresignedUrl
      """
      The presigned url object for file downloading
      """
      download: PresignedUrl
    }

    "Example type for Mutation."
    type Trip {
      """
      The serials number for a trip 
      """
      id: ID!
      """
      The flight_number listed in https://api.spacexdata.com/v2/launches
      """
      launchId: Int
      """
      The user id that Identity Provider assigned. 
      """
      userId: Int
    }
    
    "Type Query defines all query / read methods that clients can call. These methods must be implemented in resolver as well."
    type Query {
      """
      Get all presigned urls for a specific file that has been stored or will be stored on a cloud storage
      """
      presignedUrls(key: String!): PresignedUrls
      """
      Get user object from the decoded JWT
      """
      userInfo: User,
      """
      List all booked trips. This is an query example, you can remove it. 
      """
      bookedTrips: [Trip]
    }

    "Type Mutation defines all updating / write methods that clients can call. These methods must be implemented in resolver as well."
    type Mutation {
      """
      Book trips. This is an mutation example, you can remove it.
      """
      bookTrips(launchIds: [ID]!): TripUpdateResponse!
      """
      Cancel a trip. This is an mutation example, you can remove it.
      """      
      cancelTrip(launchId: ID!): TripUpdateResponse!
      """
      Sign up a user. It can help you get a mock access token from endpoint POST /mock/token 
      """
      signup(email: String): User
    }
    "The response body when bookTrips or cancelTrip method is called"
    type TripUpdateResponse {
      success: Boolean!
      message: String
    }
`;

module.exports = typeDefs;