apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <% .Name %>
  annotations:
    # nginx ingress
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # cert-manager
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: clusterissuer-letsencrypt-production
    # external-dns
    external-dns.alpha.kubernetes.io/hostname: <% index .Params `stagingBackendSubdomain` %><% index .Params `stagingHostRoot` %>
    # CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://<% index .Params `stagingFrontendSubdomain` %><% index .Params `stagingHostRoot` %>/"

spec:
  rules:
  - host: <% index .Params `stagingBackendSubdomain` %><% index .Params `stagingHostRoot` %>
    http:
      paths:
        - path: /(.*)
          backend:
            serviceName: <% .Name %>
            servicePort: http
  tls:
  - hosts:
    - <% index .Params `stagingBackendSubdomain` %><% index .Params `stagingHostRoot` %>
    secretName: <% .Name %>-tls-secret
