apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml
<%if eq (index .Params `userAuth`) "yes" %>- auth.yml
<% end %>
resources:
- ../../base
<%if eq (index .Params `userAuth`) "yes" %>## userAuth enabled - Oathkeeper proxies to backend instead of ingress
# - ingress.yml
<% else %>- ingress.yml<% end %>

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - ENVIRONMENT=staging
    - DOMAIN=<% index .Params `stagingHostRoot` %>
    - S3_BUCKET=files.<% index .Params `stagingHostRoot` %>