apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <% .Name %>

resources:
  - namespace.yml

secretGenerator:
- name: <% .Name %>
  env: secrets.env

# Don't add a suffix to the secret name
generatorOptions:
  disableNameSuffixHash: true
