version = 0.1

[stage]
[stage.deploy]
[stage.deploy.parameters]
stack_name = "<% .Name %>-stage"
s3_bucket = "<% .Name %>-serverless-<% index .Params `randomSeed` | ToLower %>"
s3_prefix = "<% .Name %>-stage"
region = "<% index .Params `region` %>"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = ["Application=<% index .Params `accountId` %>.dkr.ecr.<% index .Params `region` %>.amazonaws.com/<% .Name %>-serverless"]


[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "<% .Name %>-prod"
s3_bucket = "<% .Name %>-serverless-<% index .Params `randomSeed` | ToLower %>"
s3_prefix = "<% .Name %>-prod"
region = "<% index .Params `region` %>"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = ["Application=<% index .Params `accountId` %>.dkr.ecr.<% index .Params `region` %>.amazonaws.com/<% .Name %>-serverless"]
