apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: kratos-public
spec:
  upstream:
    url: http://kratos-public.user-auth
    stripPath: /.ory/kratos/public
    preserveHost: true
  match:
    #url: http://<backend_service_domain>/.ory/kratos/public/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: kratos-form-data
spec:
  upstream:
    url: http://kratos-admin.user-auth
    stripPath: /.ory/kratos
    preserveHost: true
  match:
    #url: http://<backend_service_domain>/.ory/kratos/self-service/<(login|registration|recovery|settings)>/flows<.*>
    methods:
      - GET
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: public-backend-endpoints
spec:
  upstream:
    url: http://<% .Name %>.<% .Name %>
    preserveHost: true
  match:
    # url: http://<backend_service_domain>/<(?!(api|\.ory\/kratos)).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: authenticated-backend-endpoints
spec:
  upstream:
    preserveHost: true
    url: http://<% .Name %>.<% .Name %>
    stripPath: /api
  match:
    # url: <backend_service_domain>/api/<.*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
    - handler: header
