## Proxy rules for Oathkeeper
## There are 4 rules for proxying 

## Public Kratos
# pattern: http://<proxy>/.ory/kratos/public
# these are the entrypoint of kratos, it handles initialization of forms
# redirections(configured in user_auth.tf from infrastructure)
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: kratos-public
spec:
  upstream:
    url: http://kratos-public.user-auth
    stripPath: /.ory/kratos/public
    preserveHost: true
  match:
    #url: http://<backend_service_domain>/.ory/kratos/public/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
## Kratos Admin
# pattern: http://<proxy>/.ory/kratos
# Note this only allows :GET requests
# Once self-service flow is initiated, a flow_id is generated
# The endpoint is used to exchange for form format / fields given a flow_id
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: kratos-form-data
spec:
  upstream:
    url: http://kratos-admin.user-auth
    stripPath: /.ory/kratos
    preserveHost: true
  match:
    #url: http://<backend_service_domain>/.ory/kratos/self-service/<(login|registration|recovery|settings)>/flows<.*>
    methods:
      - GET
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
## Backend public endpoint
# pattern: http://<proxy>/<not [/.ory/kratos and /api]>
# In example this is serves the infoPanel data, and the status endpoints that don't require user auth
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: public-backend-endpoints
spec:
  upstream:
    url: http://<% .Name %>.<% .Name %>
    preserveHost: true
  match:
    # url: http://<backend_service_domain>/<(?!(api|\.ory\/kratos)).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
## Backend User-restricted endpoint
# pattern: http://<proxy>//api
# In example this is serves the /userInfo endpoint returning the user-session's info (user_id / email)
# Note the authenticators is `cookie_session`,
# oathkeeper will verify the validity of session then pass along user-id/email in the Request Header
# these can be configured via infra's `oathkeeper-values.yml`
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: authenticated-backend-endpoints
spec:
  upstream:
    preserveHost: true
    url: http://<% .Name %>.<% .Name %>
    stripPath: /api
  match:
    # url: <backend_service_domain>/api/<.*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
    - handler: header
