apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <% .Name %>
spec:
  suspend: true
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
